seed: 2024
version: stb
device: 'cuda:0'
log_para: 1000
patch_size: 10000
mode: 'final'
num_epochs: 300
checkpoint: logs/stb/best.pth
model:
  name: 'final'
  params:
    pretrained: True
    
    mem_size1: 512
    mem_size2: 512
    mem_size3: 512
    
    mem_dim1: 256
    mem_dim2: 192
    mem_dim3: 128
    
    cls_thrs1: 0.5
    cls_thrs2: 0.5
    cls_thrs3: 0.5

    err_thrs1: 0.5
    err_thrs2: 0.5
    err_thrs3: 0.5

    den_dropout1: 0.3
    den_dropout2: 0.3
    den_dropout3: 0.3

    cls_dropout3: 0.3
    cls_dropout2: 0.3
    cls_dropout1: 0.3

    has_err_loss: False
train_dataset: &train_dataset_params
  name: 'den_cls'
  params: 
    root: './utils/data/stb'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
val_dataset: *train_dataset_params
test_dataset:
  name: 'den_cls'
  params: 
    root: './utils/data/sta'
    crop_size: 320
    downsample: 1
    is_grey: False
    unit_size: 16
    pre_resize: 1
train_loader:
  batch_size: 16
  num_workers: 16
  shuffle: True
  pin_memory: True
val_loader: &val_loader_params
  batch_size: 1
  num_workers: 4
  shuffle: False
  pin_memory: False
test_loader: *val_loader_params
optimizer:
  name: 'adamw'
  params:
    lr: &lr 0.001
    weight_decay: 0.0001
scheduler:
  name: 'onecycle'
  params:
    max_lr: *lr
    epochs: 300
    steps_per_epoch: 20
    final_div_factor: 1000